### ISSUE TITLE
modular ESC

### ISSUE THREAD

**Issue by mkeyno** [Zubax/zubax_orel#1]
Hi, sorry to open ticket for my question , actually I intend to made modular ESC in way that controller + gate driver is separated from Mosfets pcb , hence I could increase module ampere by adding parallel Mosfet in the Mosfets pcb, I really appreciated to have your advise or if you know open HW/SW sources let me know

**Comment by pavel-kirienko** [comment]
Hello. You should refer to this:

- Open source ESC firmware (BSD licensed): https://github.com/PX4/sapog
- The reference manual for the above: https://files.zubax.com/products/io.px4.sapog/Sapog_v2_Reference_Manual.pdf
- The reference hardware design for the above: https://github.com/PX4/Hardware/tree/master/sapog_reference_hardware

Hope this helps!

**Comment by mkeyno** [comment]
@pavel-kirienko  thanks to direct me to schematic reference, however I'm not sure where should I ask my question about this Sapog design , my question is : Is it possible to increase Sapog ESC amperes with add couple of Mosfet parallel to current set ?
thanks

**Comment by pavel-kirienko** [comment]
Yes, provided that you also update the current shunt, increase buffer capacitance, and probably replace the driver (at least).
